---

- name: Remove any previous copies of element-android
  delegate_to: '{{ server_ip_final }}'
  file:
    state: absent
    path: /home/developer/element-android/
  when: clone_mode is search("git")

- name: Git clone element-android repository
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  git:
    repo: '{{ element_android_repo }}'
    dest: /home/developer/element-android/
  when: clone_mode is search("git")

- name: Rsync local element-android repository
  shell: |
    rsync -av {{ local_element_android_repo_location }} {{ server_ip_final }}:/home/developer/element-android/
  when: clone_mode is search("rsync")

- name: Change permissions on element-android repository
  delegate_to: '{{ server_ip_final }}'
  file:
    path: /home/developer/element-android/
    owner: developer
    group: developer
    recurse: yes
  when: clone_mode is search("rsync")

- set_fact:
    slash: '\'
  when: sign_packages | bool

- name: Copy Android signing key to compile machine
  delegate_to: '{{ server_ip_final }}'
  copy:
    src: '{{ private_keystore_file }}'
    dest: '/home/developer/element-android/vector/'
    owner: developer
    group: developer
    mode: '0600'
  when: sign_packages | bool

- name: Replace keyAlias value in build.gradle
  delegate_to: '{{ server_ip_final }}'
  replace:
    path: '/home/developer/element-android/vector/build.gradle'
    regexp: '            keyAlias project.property\(\"signing.element.keyId\"\)$'
    replace: "            keyAlias '{{ private_keystore_alias }}'"
  when: sign_packages | bool

- name: Replace keyPassword value in build.gradle
  delegate_to: '{{ server_ip_final }}'
  replace:
    path: '/home/developer/element-android/vector/build.gradle'
    regexp: '            keyPassword project.property\(\"signing.element.keyPassword\"\)$'
    replace: "            keyPassword '{{ private_keystore_password }}'"
  when: sign_packages | bool

- name: Replace storeFile value in build.gradle
  delegate_to: '{{ server_ip_final }}'
  replace:
    path: '/home/developer/element-android/vector/build.gradle'
    regexp: '            storeFile file\(project.property\("signing.element.storePath"\)\)$'
    replace: "            storeFile file('./{{ private_keystore_file | basename }}')"
  when: sign_packages | bool

- name: Replace storePassword value in build.gradle
  delegate_to: '{{ server_ip_final }}'
  replace:
    path: '/home/developer/element-android/vector/build.gradle'
    regexp: '            storePassword project.property\("signing.element.storePassword"\)$'
    replace: "            storePassword '{{ private_keystore_password }}'"
  when: sign_packages | bool

- name: Allow signing of release version in build.gradle
  delegate_to: '{{ server_ip_final }}'
  replace:
    path: '/home/developer/element-android/vector/build.gradle'
    after: '        release {'
    regexp: '            \/\/ signingConfig signingConfigs.release$'
    replace: '            signingConfig signingConfigs.release'
  when: sign_packages | bool

- name: Disallow signing of debug version in build.gradle
  delegate_to: '{{ server_ip_final }}'
  replace:
    path: '/home/developer/element-android/vector/build.gradle'
    before: '        release {'
    regexp: '            signingConfig signingConfigs.debug'
    replace: '            // signingConfig signingConfigs.debug$'
  when: sign_packages | bool

- debug: msg="Time before compilation starts {{ ansible_date_time.time }}"

- name: Compile Element-Android Gplay (debug) with Gradle (Can take up to 30mins!)
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell:
    cmd: ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleGplayDebug -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace
    chdir: /home/developer/element-android/
  async: 1800
  poll: 15
  when: ( build_mode is search("debug") ) and ( build_gplay | bool )

# Debug Gplay build
# ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleGplayDebug -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace

# Outputs at:
#./vector/build/outputs/apk/gplay/debug/vector-gplay-armeabi-v7a-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-x86_64-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-x86-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-arm64-v8a-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-universal-debug.apk

- name: Compile Element-Android Gplay (release) with Gradle (Can take up to 60mins!)
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell:
    cmd: ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleGplay -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace
    chdir: /home/developer/element-android/
  async: 3600
  poll: 15
  when: ( build_mode is search("release") ) and ( build_gplay | bool )

# Release Gplay build
# ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleGplay -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace

# Outputs at:
#./vector/build/outputs/apk/gplay/release/vector-gplay-armeabi-v7a-release-unsigned.apk
#./vector/build/outputs/apk/gplay/release/vector-gplay-x86_64-release-unsigned.apk
#./vector/build/outputs/apk/gplay/release/vector-gplay-universal-release-unsigned.apk
#./vector/build/outputs/apk/gplay/release/vector-gplay-x86-release-unsigned.apk
#./vector/build/outputs/apk/gplay/release/vector-gplay-arm64-v8a-release-unsigned.apk

- name: Compile Element-Android FDroid (debug) with Gradle (Can take up to 30mins!)
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell:
    cmd: ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleFdroidDebug -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace
    chdir: /home/developer/element-android/
  async: 1800
  poll: 15
  when: ( build_mode is search("debug") ) and ( build_fdroid | bool )

# Debug Fdroid build
# ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleFdroidDebug -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace

# Outputs at:
#./vector/build/outputs/apk/fdroid/debug/vector-fdroid-armeabi-v7a-debug.apk
#./vector/build/outputs/apk/fdroid/debug/vector-fdroid-x86_64-debug.apk
#./vector/build/outputs/apk/fdroid/debug/vector-fdroid-x86-debug.apk
#./vector/build/outputs/apk/fdroid/debug/vector-fdroid-universal-debug.apk
#./vector/build/outputs/apk/fdroid/debug/vector-fdroid-arm64-v8a-debug.apk

- name: Compile Element-Android FDroid (release) with Gradle (Can take up to 60mins!)
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell:
    cmd: ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleFdroid -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace
    chdir: /home/developer/element-android/
  async: 3600
  poll: 15
  when: ( build_mode is search("release") ) and ( build_fdroid | bool )

# Release Fdroid build
# ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew assembleFdroid -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace

# Outputs at:
#./vector/build/outputs/apk/fdroid/release/vector-fdroid-universal-release-unsigned.apk
#./vector/build/outputs/apk/fdroid/release/vector-fdroid-armeabi-v7a-release-unsigned.apk
#./vector/build/outputs/apk/fdroid/release/vector-fdroid-x86-release-unsigned.apk
#./vector/build/outputs/apk/fdroid/release/vector-fdroid-arm64-v8a-release-unsigned.apk
#./vector/build/outputs/apk/fdroid/release/vector-fdroid-x86_64-release-unsigned.apk

- name: Compile Element-Android Gplay (bundle) with Gradle (Can take up to 60mins!)
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell:
    cmd: ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew bundleGplay -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace
    chdir: /home/developer/element-android/
  async: 3600
  poll: 15
  when: ( build_mode is search("bundle") ) and ( build_gplay | bool )

# Bundle Gplay build
# ANDROID_SDK_ROOT=/home/developer/android-sdk ./gradlew bundleGplay -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace

# Outputs at:
#./vector/build/outputs/bundle/gplayRelease/vector-gplay-release.aab
#./vector/build/outputs/bundle/gplayDebug/vector-gplay-debug.aab
#./vector/build/intermediates/intermediary_bundle/gplayRelease/packageGplayReleaseBundle/intermediary-bundle.aab
#./vector/build/intermediates/intermediary_bundle/gplayRelease/shrinkBundleGplayReleaseResources/intermediary-bundle.aab
#./vector/build/intermediates/intermediary_bundle/gplayDebug/intermediary-bundle.aab

- name: Collect list of generated .apk files
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell: |
    find /home/developer/element-android/ -name *.apk
  register: output_files
  when: ( build_mode is search("release") ) or ( build_mode is search("debug") )

- name: Collect list of generated .aab files
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell: |
    find /home/developer/element-android/ -name *.aab
  register: output_files
  when: ( build_mode is search("bundle") )

- name: Fetch .apk/.aab outputs of compilation
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  fetch:
    src: '{{ item }}'
    dest: ./outputs/
    flat: yes
  with_items: '{{ output_files.stdout_lines }}'
