---

- name: Compile Element Android with Gradle (Can take up to 20mins!)
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell:
    cmd: ANDROID_SDK_ROOT=/usr/lib/android-sdk ./gradlew assembleGplayDebug -Porg.gradle.jvmargs=-Xmx2g -Porg.gradle.parallel=false --stacktrace
    chdir: /home/developer/element-android/
  async: 1200
  poll: 15

#
# See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
#
# BUILD SUCCESSFUL in 12m 4s
# 198 actionable tasks: 198 executed

# Outputs at:

#./vector/build/outputs/apk/gplay/debug/vector-gplay-armeabi-v7a-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-x86_64-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-x86-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-arm64-v8a-debug.apk
#./vector/build/outputs/apk/gplay/debug/vector-gplay-universal-debug.apk


# print these fullpaths into a list

# developer@compile-element:~/element-android$ find ./ -name *.apk

- name: Collect list of generated .apk files
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell: |
    find /home/developer/element-android/ -name *.apk
  register: apk_files

# fetch one by one

- name: Fetch .apk outputs of compilation
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  fetch:
    src: '{{ item }}'
    dest: ./outputs/
    flat: yes
  with_items: '{{ apk_files.stdout_lines }}'