

# Server Setup
- include_tasks:
    file: "{{ role_path }}/tasks/setup_server.yml"
    apply:
      tags:
        - setup-server
  tags:
    - setup-server

# Setup Developer Environment
- include_tasks:
    file: "{{ role_path }}/tasks/setup_developer_environment.yml"
    apply:
      tags:
        - setup-server
  tags:
    - setup-server

# Compile Element Android
- include_tasks:
    file: "{{ role_path }}/tasks/compile_element_android.yml"
    apply:
      tags:
        - compile-element-android
  tags:
    - compile-element-android