---

- name: Ensure group "developer" exists
  delegate_to: "{{ server_ip_final }}"
  group:
    name: developer
    gid: 1001
    state: present

- name: Add the disabled user account 'developer' with a specific uid and a primary group of 'developer'
  delegate_to: "{{ server_ip_final }}"
  user:
    name: developer
    comment: Developer user account for compiling applications.
    shell: /bin/bash
    uid: 1001
    group: developer

# Latest:
# https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip	1.8.0
# 0bebf59339eaa534f4217f8aa0972d14dc49e7207be225511073c661ae01da0a

# Nov 1st 2022:
# https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip	???
# 2ccbda4302db862a28ada25aa7425d99dce9462046003c1714b059b5c47970d8

# Original:
# https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
# d71f75333d79c9c6ef5c39d3456c6c58c613de30e6a751ea0dbd433e8f8b9cbf


- name: Download latest version of Androids commandlinetools
  get_url:
    url: https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
    dest: ./downloads/commandlinetools-linux-8512546_latest.zip
    checksum: sha256:2ccbda4302db862a28ada25aa7425d99dce9462046003c1714b059b5c47970d8

- name: Copy latest version of Androids commandlinetools to compile machine
  delegate_to: '{{ server_ip_final }}'
  copy:
    src: ./downloads/commandlinetools-linux-8512546_latest.zip
    dest: /home/developer/commandlinetools-linux-8512546_latest.zip
    owner: developer
    group: developer
    mode: '0644'

- name: Extract latest version of Androids commandlinetools
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell: |
    unzip -oq /home/developer/commandlinetools-linux-8512546_latest.zip -d /home/developer/

- name: Automatically accept Googles android SDK license agreement without reading it
  delegate_to: '{{ server_ip_final }}'
  become: yes
  become_user: developer
  shell: |
    yes | /home/developer/cmdline-tools/bin/sdkmanager --licenses --sdk_root=/home/developer/android-sdk
