
# Spawn DigitalOcean Droplet
- import_tasks: "{{ role_path }}/tasks/spawn_droplet.yml"
  tags: spawn-droplet

# Check and Save Compile Servers IP
- import_tasks: "{{ role_path }}/tasks/save_server_ips.yml"
  tags: save_ips

# Delete DigitalOcean Droplet
- import_tasks: "{{ role_path }}/tasks/delete_droplet.yml"
  tags: delete-droplet